export const FETCH_CONTACTS = "FETCH_CONTACTS";
export const ON_CONTACT_SELECT = "ON_CONTACT_SELECT";
export const ON_HANDLE_INFO_INPUT_CHANGE = "ON_HANDLE_INFO_INPUT_CHANGE ";
export const ON_EDITE_CONFIRM = "ON_EDITE_CONFIRM ";
export const ON_CONTACT_ADD = "ON_CONTACT_ADD";
export const ON_FILTER = "ON_FILTER";
